spring:
  application:
    name: customer-service
  
          
#
# This is Eureka Client to Eureka Server at 8761
eureka:
  client:
    instance:
    hostname: localhost
    fetchRegistry: 'true'
    registerWithEureka: 'true'
    preferIpAddress: 'true'
    serviceUrl:
      defaultZone: http://localhost:8761/eureka



